name: Deploy Site after Push to master branch
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v4
      - uses: actions/setup-node@master
      - name: Installing project dependencies
        run: npm install
      - name: Building the project
        run: npm run production
      - name: Copy .env
        run: cp .env.example .env
      - name: Add .env variables
        run : |
          echo APP_ENV=production >> .env
          echo APP_DEBUG=false >> .env
          echo APP_URL=https://penalito.com >> .env
      - name: Install Dependencies
        run: composer install --no-dev
      - name: Generate key
        run: php artisan key:generate
      - name: Statamic upgrade
        run: composer update statamic/cms --with-dependencies
      - name: Cache clear & stache clear
        run: php artisan cache:clear && php please stache:clear && php please cache:clear
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
